# Generated by Django 4.1.2 on 2023-08-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_tag_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
