# Generated by Django 4.1.2 on 2023-08-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_tag_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
